# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JUUxF1mp5iW9ZEoYPMTTWx_qic8EBEIk
"""

!pip install streamlit
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

st.set_page_config(page_title="Dashboard Analisis Siswa", layout="wide")
st.title("📊 Dashboard Analisis Hasil Simulasi Siswa")

file_path = "/content/data_simulasi_50_siswa_20_soal.xlsx"

try:
    df = pd.read_excel(file_path)
    df.columns = df.columns.str.strip()
    indikator = df.apply(pd.to_numeric, errors="coerce")
    st.success(f"File '{file_path}' berhasil dimuat ✅")
except FileNotFoundError:
    st.error(f"Error: File tidak ditemukan di '{file_path}'. Pastikan file ada di lokasi tersebut.")
except Exception as e:
    st.error(f"Terjadi kesalahan saat membaca file: {e}")

mean_scores = indikator.mean()
total_avg = mean_scores.mean()
ikm = (total_avg / 4) * 100

def kategori(x):
    if x >= 80:
        return "Sangat Baik"
    elif x >= 65:
        return "Baik"
    elif x >= 50:
        return "Cukup"
    else:
        return "Kurang"

col1, col2, col3 = st.columns(3)
col1.metric("Rata-rata Skor", f"{total_avg:.2f}")
col2.metric("Kategori", kategori(ikm))
col3.metric("Jumlah Siswa", len(df))

st.divider()

st.subheader("🎯 Analisis GAP per Soal")

gap = 4 - mean_scores
prioritas = gap.idxmax()

fig1, ax1 = plt.subplots()
gap.sort_values(ascending=False).plot(kind="bar", ax=ax1)
ax1.set_ylabel("Nilai GAP")
plt.xticks(rotation=45)
st.pyplot(fig1)

st.warning(f"Prioritas perbaikan: {prioritas}")

st.divider()

st.subheader("🔗 Heatmap Korelasi")

corr = indikator.corr()

fig2, ax2 = plt.subplots(figsize=(8,6))
sns.heatmap(corr, cmap="coolwarm", ax=ax2)
st.pyplot(fig2)

st.divider()

st.subheader("⚖️ Analisis Regresi (Soal Terakhir sebagai Target)")

X = sm.add_constant(indikator.iloc[:, :-1])
y = indikator.iloc[:, -1]

model = sm.OLS(y, X, missing="drop").fit()

st.info(f"Nilai R-Squared: {model.rsquared:.3f}")

top_coef = model.params[1:].sort_values(ascending=False).head(5)
st.write("Top 5 Soal Paling Berpengaruh:")
st.dataframe(top_coef)

st.divider()

st.subheader("👥 Segmentasi Siswa (K-Means)")

jumlah_cluster = st.slider("Pilih jumlah cluster", 2, 5, 3)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(indikator.fillna(0))

kmeans = KMeans(n_clusters=jumlah_cluster, random_state=42, n_init=10)
cluster = kmeans.fit_predict(X_scaled)

indikator["Cluster"] = cluster

st.write("Distribusi Cluster:")
st.dataframe(indikator["Cluster"].value_counts())

fig3, ax3 = plt.subplots()
indikator["Cluster"].value_counts().plot(kind="bar", ax=ax3)
st.pyplot(fig3)

st.success("Dashboard siap digunakan 🎉")